server:
  port: 56020

#服务提供方IP和端口
#provider:
  #address: 127.0.0.1:56010
spring:
  application:
    name: nacos-restful-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #服务发现中心地址

#配置负载均衡策略
nacos-restful-provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
# dubbo配置
dubbo:
  application:
    name: nacos-restful-consumer
  registry:
    address: nacos://127.0.0.1:8848